config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { }
  get 'about/privacy'
  post '/signup' => 'splash#signup', as: :splash_signup
  get '/splash' => 'splash#index'
  root 'splash#index'
  get '/setup/open' => 'setup#open'
  post '/setup/generate' => 'setup#generate'
  get '/setup' => 'setup#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/performance.rb
class Performance < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_one_attached :image
  before_save :set_slug

  def set_slug
  	self.slug = self.name.downcase.gsub(" ", "_").gsub(',',"").gsub("#","").gsub("[^a-z0-9\s-]", "")
  end

  def to_param
    slug
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def privacy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate
  
  def authenticate
    unless ENV['HTTP_AUTH_USERNAME'].blank? or ENV['HTTP_AUTH_PASSWORD'].blank?
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_AUTH_USERNAME'] && password == ENV['HTTP_AUTH_PASSWORD']
      end
    end
  end
  
end

app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
  before_action :set_performance, only: [:show, :edit, :update, :destroy, :delete_image_attachment]
  
  private

  def set_performance
    @performance = Performance.find_by_slug(params[:id])
  end 

end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  before_action :require_local!
  layout :false

  def index
    load_generators
    load_specs
    load_docs
    load_packages
  end

  def open
    spec = Bundler.definition.specs[params[:gem]].first
    if spec
      system( "subl #{spec.gem_dir}/ || sublime #{spec.gem_dir}/")
    end

    redirect_to :root
  end
  
  protected

  def require_local!
    unless local_request?
      redirect_to root_url, error: "This information is only available to local requests"
    end
  end

  def local_request?
    Rails.application.config.consider_all_requests_local || request.local?
  end

  def load_specs
    @specs = Bundler.definition.specs.to_a
  end

  def load_docs
    @docs = files
  end

  def load_generators
    @generators = []
    @files = Dir.glob( File.join( $LOAD_PATH.select{ |x| x =~ /happy_seed/}.first, "**", "*_generator.rb" ))
    @files.each do |file|
      require file
      class_name =  file.gsub( /.*\//, "" ).gsub( /.rb/,"" )
      cls = eval "HappySeed::Generators::#{class_name.classify}"
      @generators << cls if cls.respond_to? :fingerprint
    end
  end

  def load_packages
    @packages = []

    @packages << { title: "Splash Page", desc: "This is a basic splash page", gens: ["simple_cms", "roles"] }
    @packages << { title: "Forum Site", desc: "This is a basic splash page", gens: ["simple_cms", "twitter", "react"] }
    @packages << { title: "Ecommerce", desc: "This is a basic splash page", gens: ["simple_cms", "twitter", "react"] }
    @packages << { title: "Photo Sharing", desc: "This is a basic splash page", gens: ["simple_cms", "twitter", "react"] }
  end
  
  def files
    docs = Dir.glob(File.join( Rails.root, "docs/README.*" )).collect do |file|
      name = file.gsub( /.*README.\d\d./, "happy_seed:" ).gsub( /.rdoc/, "" )
      html = RDiscount.new( File.read( file ) ).to_html
      { name: name, html: html }
    end
  end
end

app/controllers/splash_controller.rb
class SplashController < ApplicationController
  skip_before_action :authenticate

  def index
  end

  def signup
    if ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID'].blank? or ENV['MAILCHIMP_API_KEY'].blank?

      @message = "The MAILCHIMP_API_KEY and MAILCHIMP_SPLASH_SIGNUP_LIST_ID environment variables need to be set for mailing list signup to work! If you don't want this feature, you can just remove the mailing list signup feature from app/views/splash/index.html.haml"

    else
      begin

        gb = Gibbon::Request.new(api_key: ENV['MAILCHIMP_API_KEY'])

       gb.lists(ENV['MAILCHIMP_SPLASH_SIGNUP_LIST_ID']).members.create(
         body: {
           email_address: params[:signup_email],
           status: "pending"
           }
         )

        @message = 'Thanks for signing up!'

      rescue StandardError => e
        @error = true

        if e.message =~ /is already subscribed to the list/
          @message = "You're already signed up to receive updates. Thanks for your enthusiasm!"
        else
          @message = "Oops! Looks like we ran into an error. How embarrassing. Please try again later!"
        end

      end
    end
  end


  private

    def gem_available?(name)
       Gem::Specification.find_by_name(name)
    rescue Gem::LoadError
       false
    rescue
       Gem.available?(name)
    end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
      # allow either standard rails flash category symbols...
      when :notice then "info"
      when :success then "success"
      when :alert then "warning"
      when :error then "danger"
      # ... or bootstrap class symbols
      when :info then "info"
      when :warning then "warning"
      when :danger then "danger"
      # and default to being alarming
      else "danger"
    end
  end

  def page_title
    @title || controller_name.gsub( /Controller/, "" ).humanize
  end
end

app/helpers/performances_helper.rb
module PerformancesHelper
end

app/views/about/privacy.html.haml
%h1 About#privacy
%p Find me in app/views/about/privacy.html.haml

app/views/application/_account_dropdown.html.haml
%li.dropdown
  %a.dropdown-toggle{ "href" => "#", "data-toggle"=>"dropdown", "role" => "button", "aria-expanded"=>"false"}
    Account <span class="caret"></span>
  %ul.dropdown-menu
    - if user_signed_in?
      = link_to 'Profile', edit_user_registration_path
      = link_to 'Sign Out', destroy_user_session_path, :method=>:delete
    - else
      / CONNECT
      = link_to 'Sign In', new_user_session_path
      = link_to 'Sign Up', new_user_registration_path

app/views/application/_chromeframe.html.haml
/[if lt IE 7 ]
  %p.chromeframe
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.

app/views/application/_flashes.html.haml
- if !flash.empty?
  .container#flash
    - flash.each do |key, value|
      = alert_box value, context: flash_class(key), dismissible: true

app/views/application/_footer.html.haml
%footer#footer
  .container
    .row
      .col-xs-6
        %h3 AppName
      .col-xs-6.text-right
        %small.copyright
          T, Copyright &copy; #{ Date.today.year }

app/views/application/_head.html.haml
%head
  %meta{ :charset => 'utf-8' }/
  %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

  = display_meta_tags :site => 'Seed Site', :title => page_title, :reverse => true

  %meta{ :name => 'description', :content => '' }/
  %meta{ :name => 'viewport', :content => 'width=device-width' }/

  = render 'stylesheets'
  = javascript_include_tag 'modernizr'

  = csrf_meta_tag

app/views/application/_header.html.haml
= navbar position: :static do
  = vertical do
    = link_to root_path do
      %span.glyphicon.glyphicon-cloud
      Home
  = horizontal do
    = nav class: 'navbar-right' do
      = link_to 'Contact', ""
      = link_to 'About', ""
      = render partial: "application/account_dropdown"

app/views/application/_javascripts.html.haml
= javascript_include_tag 'application'

-#  Append your own using content_for :javascripts
= yield :javascripts

-# Google Analytics
- if !ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{ ENV['GOOGLE_ANALYTICS_SITE_ID'] }', 'auto');
    ga('send', 'pageview');

app/views/application/_stylesheets.html.haml
= stylesheet_link_tag 'application', :media => nil

-# Append your own using content_for :stylesheets
= yield :stylesheets

app/views/layouts/application.html.haml
!!! 5
%html.no-js
  = render 'head'

  %body{ :class => "#{ controller.controller_name }" }
    = render 'chromeframe'
    = render 'header'
    = render 'flashes'

    = yield

    = render 'footer'

    -# Javascript at the bottom for fast page loading
    = render 'javascripts'

app/views/layouts/splash.html.haml
!!! 5
%html.no-js
  %head
    %meta{ :charset => 'utf-8' }/
    %meta{ 'http-equiv' => 'X-UA-Compatible', :content => 'IE=edge,chrome=1' }/

    = display_meta_tags :site => 'Seed Site', :title => page_title, :reverse => true

    %meta{ :name => 'description', :content => '' }/
    %meta{ :name => 'viewport', :content => 'width=device-width' }/
    %link{:href => "https://s3.amazonaws.com/mimistheater/small-logo.png", :rel => "shortcut icon", :type => "image/x-icon"}/

    = stylesheet_link_tag 'splash', :media => nil

    -# Append your own using content_for :stylesheets
    = yield :stylesheets
    = javascript_include_tag 'modernizr'

    = csrf_meta_tag

  %body.splash#top{ data: { spy: "scroll", target: "#navbar"} }
    = render 'chromeframe'
    = render 'flashes'

    %header.slideup.affix-top{ data: { spy: "affix", "offset-top": 10 } }
      = navbar id: "navbar", fluid: true, position: :top, padding: 0 do
        = vertical do
          = link_to "#top" do
            mimi's community theater
        = horizontal do
          = nav class: 'navbar-right' do
            = link_to "(407) 864-5029", "#"
            = link_to "About", "#about"
            = link_to "Contact", "#contact"

    = yield


    -# Javascript at the bottom for fast page loading
    = render 'javascripts'
    = javascript_include_tag 'scrollReveal.js'
    :javascript
        $(function() { 
          window.scrollReveal = new scrollReveal();
          $("#top a[href^='#']").on('click', function(e) {
            e.preventDefault();

            // store hash
            var hash = this.hash;

            var nav_height = $("nav").height();

            // animate
            $('html, body').animate({
              scrollTop: $(this.hash).offset().top - nav_height
            }, 500, function(){
              // when done, add hash to url
              // (default click behaviour)
              window.location.hash = hash;
            });
          });
        });

app/views/setup/index.html.haml
!!!
%html
  %head
    %title HappySeed Generator setup page
    = javascript_include_tag 'application'
    = csrf_meta_tags 
    %script{:src=>"//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"}
    %link{ href: "//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css", rel: "stylesheet"}
    :css
      body { padding-top: 70px; }
      .row { padding-top: 70px; }
      #nav { margin-top: 25px; }
      @media (max-width: 768px) {
        .affix {
            position: static;
        }
      }

  %body
    = render partial: "application/header"
    = render partial: "application/flashes"
    %nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          %button.navbar-toggle.collapsed{ type: "button", data: { toggle: "collapse" }, "aria-expanded": false }
            %span.sr-only Toggle Navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{ href: "#" } Seed Admin
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              %a{ href: "#packages"} Packages
            %li
              %a{ href: "#generators" } Generators
            %li
              %a{ href: "#gems" } Gems
            %li
              %a{ href: "/rails/mailers"}Mailer Previews
            %li.dropdown
              %a.dropdown-toggle{ href: "#", data: { toggle: "dropdown"}}
                Documentation
                %span.caret
              %ul.dropdown-menu
                - @docs.each do |f|
                  %li
                    %a{ href: "##{f[:name]}"}= f[:name]

    - if !flash.empty?
      .container#flash
        - flash.each do |key, value|
          %p= value

    .container
      .row#packages
        .jumbotron
          %h1 Here are some built in awesomeness

          %p It's so great, totally fer sure.

      .row
        - @packages.each do |package|
          .col-sm-3
            .panel.panel-default
              .panel-heading
                %h3.panel-title
                  = package[:title]
              .panel-body
                %p= package[:desc]

                %ul
                  - package[:gens].each do |gen|
                    %li= gen

                %button.btn.btn-primary Generate!

      .row#generators
        .col-xs-12
          %h2 Available seed generators

          %table.table.table-striped.table-bordered
            %tr
              %th Genenerator
              %td Already run?
              %th Action
            - @generators.each do |gen|
              %tr
                %th= gen.to_s
                %td= gen.fingerprint
                %td
                  - unless gen.fingerprint
                    = button_to "Run generator", setup_generate_path( gen.to_s ), class: "btn btn-primary"

      .row#gems
        .col-xs-12
          %h2 Installed Gems

          %table.table.table-striped.table-bordered
            %tr
              %th Gem
              %th Summary
              %th Dependancies

            - @specs.each do |spec|
              %tr
                %td
                  = link_to "#{spec.name} #{spec.version}", spec.homepage
                  %br
                  %img{ src: "https://badge.fury.io/rb/#{spec.name}.svg" }

                %td= link_to spec.summary, setup_open_path( :gem => spec.name ), "data-title": spec.description, "data-toggle": "tooltip", "data-placement": "bottom"
                %td
                  -if spec.dependencies.size > 0

                    .dropdown
                      %button.btn.btn-default.dropdown-toggle{ type: "button", "data-toggle": "dropdown", "aria-expanded": "true" }
                        Dependencies
                        %span.caret

                      %ul.dropdown-menu.dropdown-menu-right
                        - spec.dependencies.each do |dep|
                          - spec = Bundler.definition.specs[dep.name].first

                          %li{ class: "#{spec.nil? ? 'disabled' : ''}" }
                            - if spec
                              = link_to "#{dep.name} (#{dep.type}) #{dep.requirements_list.join( ", ")}", spec.homepage, "data-title": spec.description, "data-toggle": "tooltip", "data-placement": " auto"
                            - else
                              = link_to dep.name, "#"


        / rdocs
      - @docs.each do |f|
        .row
          %h3
            %a{ name: "#{f[:name]}"}= f[:name]

          ~ f[:html].html_safe

:javascript
  $( function() {
    $('[data-toggle="tooltip"]').tooltip();  
  });

app/views/splash/_environment_checks.html.haml
%ul.list-group

  - if ENV['AWS_ACCESS_KEY_ID'].blank? or ENV['AWS_SECRET_ACCESS_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 AWS
      You haven't set up your AWS account in this environment! Set the <code>AWS_ACCESS_KEY_ID</code> and <code>AWS_SECRET_ACCESS_KEY</code> environment variables to configure AWS. You should have the client sign up and follow the instructions below.
  - else
    %li.list-group-item.list-group-item-success
      %h4 AWS
      Your AWS account is configured for this environment!



  - if ENV['GOOGLE_ANALYTICS_SITE_ID'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Google Analytics
      You haven't set up a Google Analytics account in this environment! Set the <code>GOOGLE_ANALYTICS_SITE_ID</code> environment variables to configure Google Analytics. You should ask the client to <a href="http://google.com/analytics/" target="_blank">set up a Google Analytics account</a>.
  - else
    %li.list-group-item.list-group-item-success
      %h4 Google Analytics
      Your Google Analytics account is configured for this environment!



  - unless @tracker_gems.values.any?
    %li.list-group-item.list-group-item-danger
      %h4 Exception Tracking
      You haven't set up an exception tracker! May I recommend <a href="https://addons.heroku.com/honeybadger" target="_blank">Honeybadger</a>?
  - else
    %li.list-group-item.list-group-item-success
      %h4 Exception Tracking
      Found exception tracker gems(s):
      = @tracker_gems.select{|k,v| v}.keys.join(', ')



  - if ENV['MAILCHIMP_API_KEY'].blank?
    %li.list-group-item.list-group-item-danger
      %h4 Mailchimp
      <p>You haven't set up a Mailchimp account in this environment! Have the client create an account at <a href="http://mailchimp.com" target="_blank">mailchimp.com</a> and set the <code>MAILCHIMP_API_KEY</code> environment variables to configure Mailchimp.</p>
      <p>Once a Mailchimp account is configured, you'll need to create a list through the web interface and set the <code>MAILCHIMP_SPLASH_SIGNUP_LIST_ID</code> environment variable to the list id (ten-digit hex id visible in the List name &amp; defaults tab).</p>
  - else
    %li.list-group-item.list-group-item-success
      %h4 Mailchimp
      Your Mailchimp account is configured for this environment!

app/views/splash/index.html.haml
%section.lightimage
  .container
    .row
      .inner-column
        =image_tag 'https://s3.amazonaws.com/mimistheater/mimi_logo_sm.png'
        %h1 Mimis's Community Theater

        %p.info 230 W Bay St Winter Garden, FL 34787

        = link_to "Next Showing", root_url, class: "btn btn-primary btn-lg colors"

%section.colored.colors#about
  .container
    .row
      .inner-column
        
        %h2 Let’s start a community theater in Winter Garden!
        .flex.corner-2
          =image_tag "https://s3.amazonaws.com/mimistheater/mimiandbart.jpg", class: 'img-responsive'

        %p Bart and I retired a couple years ago, then said, “Let’s start a community theater in Winter Garden”. We wanted a place where local people could get together to share their passion of live community theater. No experience or age limits! Everybody is invited to come out to play! A blessing was offered to us and everyone in the community! The Winter Garden Masonic Lodge offered us a home! A place to rehearse and to performe our shows. We are now well into our second year! Thank you to everyone that has come on board. We couldn’t have done it without you! 

        = link_to "Get Involved", root_url, class: "btn btn-primary-inverted btn-lg"

app/views/splash/signup.js.erb
<% if @error %>
  $('#signup').addClass('has-error');
<% else %>
  $('#signup').removeClass('has-error');
  $('#signup_email').val('');
<% end %>

$('#signup-message').text("<%= j @message.html_safe %>").hide().slideDown('fast');